"""Convert result files written with the one-way-time convention (T_old = one-way travel time,
phi in [0, 2)) to the full-period convention (T = 2 T_old, phi = phi_old / 2 in [0, 1)).

usage: python scripts/convert_legacy.py results/grid [results/sens ...]
Files already converted (r["T_convention"] == "period") are left untouched. Pickles are renamed
sol_<tag>_T<2T>_m<m>_phi<phi/2>.pkl; rows_*.csv are regenerated by run_grid.py (which re-reads pickles).
"""
import glob, os, pickle, sys, re

for d in sys.argv[1:]:
    for f in sorted(glob.glob(os.path.join(d, "sol_*.pkl"))):
        r = pickle.load(open(f, "rb"))
        if r.get("T_convention") == "period":
            continue
        T_old = r["T"]
        r["T"] = 2.0 * T_old
        r["phi_l"] = r["phi_l"] / 2.0
        r["phi_c"] = r["phi_c"] / 2.0
        r["phi0"] = r.get("phi0", 0.0) / 2.0
        r["T_convention"] = "period"
        if r.get("params", {}).get("fixed_release_phase") is not None:
            r["params"]["fixed_release_phase"] = r["params"]["fixed_release_phase"] / 2.0
        r["params"]["release_deadline_factor"] = 1.0
        m = re.match(r"sol_(.+)_T([0-9.]+)_m([0-9.]+)_phi([0-9.]+)\.pkl$", os.path.basename(f))
        tag, _, mm, _ = m.groups()
        new = os.path.join(d, f"sol_{tag}_T{r['T']:g}_m{float(mm):g}_phi{r['phi_l']:.3f}.pkl")
        pickle.dump(r, open(new, "wb"))
        if new != f:
            os.remove(f)
        print(os.path.basename(f), "->", os.path.basename(new))
    for f in glob.glob(os.path.join(d, "rows_*.csv")) + glob.glob(os.path.join(d, "grid_*.csv")):
        os.rename(f, f + ".legacy")
print("converted")
